name: Hoonology
title: Hoonology | Welcome to Hoonology's Blog !
description: Hoonology changes whole world.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: mase306@gmail.com
# See: https://disqus.com/
disqus_username: hoonology
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
